export type PaintRange = {
  brand: 'Citadel' | 'Army Painter';
  range: string;
  paints: string[];
};

export const PAINT_CATALOG: PaintRange[] = [
  {
    brand: 'Citadel',
    range: 'Base',
    paints: [
      'Abaddon Black',
      'Corax White',
      'Rhinox Hide',
      'Mephiston Red',
      'Khorne Red',
      'Macragge Blue',
      'Kantor Blue',
      'Caliban Green',
      'Waaagh! Flesh',
      'Retributor Armour',
      'Leadbelcher',
      'Warplock Bronze',
      'Ushabti Bone',
      'Zandri Dust',
      'Averland Sunset',
      'Screamer Pink',
      'Naggaroth Night',
      'Steel Legion Drab',
    ],
  },
  {
    brand: 'Citadel',
    range: 'Layer',
    paints: [
      'White Scar',
      'Evil Sunz Scarlet',
      'Wild Rider Red',
      'Troll Slayer Orange',
      'Flash Gitz Yellow',
      'Yriel Yellow',
      'Sotek Green',
      'Warpstone Glow',
      'Teclis Blue',
      'Hoeth Blue',
      'Alaitoc Blue',
      'Fenrisian Grey',
      'Ironbreaker',
      'Runefang Steel',
      'Auric Armour Gold',
      'Sycorax Bronze',
      'Cadian Fleshtone',
      'Kislev Flesh',
    ],
  },
  {
    brand: 'Citadel',
    range: 'Shade',
    paints: [
      'Nuln Oil',
      'Agrax Earthshade',
      'Reikland Fleshshade',
      'Seraphim Sepia',
      'Carroburg Crimson',
      'Drakenhof Nightshade',
      'Biel-Tan Green',
      'Athonian Camoshade',
      'Casandora Yellow',
    ],
  },
  {
    brand: 'Citadel',
    range: 'Contrast',
    paints: [
      'Black Templar',
      'Blood Angels Red',
      'Space Wolves Grey',
      'Talassar Blue',
      'Ork Flesh',
      'Wyldwood',
      'Skeleton Horde',
      'Aggaros Dunes',
      'Gore-Grunta Fur',
      'Snakebite Leather',
      'Iyanden Yellow',
      'Terradon Turquoise',
    ],
  },
  {
    brand: 'Citadel',
    range: 'Technical',
    paints: [
      'Blood for the Blood God',
      'Nihilakh Oxide',
      'Typhus Corrosion',
      'Astrogranite',
      'Armageddon Dust',
      'Nurgle\'s Rot',
      'Lahmian Medium',
    ],
  },
  {
    brand: 'Citadel',
    range: 'Dry',
    paints: [
      'Necron Compound',
      'Terminatus Stone',
      'Administratum Grey',
      'Ushabti Bone Dry',
      'Screaming Skull',
    ],
  },
  {
    brand: 'Army Painter',
    range: 'Warpaints Fanatic',
    paints: [
      'Matt Black',
      'Matt White',
      'Wolf Grey',
      'Skeleton Bone',
      'Angel Green',
      'Army Green',
      'Necrotic Flesh',
      'Dragon Red',
      'Greedy Gold',
      'Plate Mail Metal',
      'Gun Metal',
      'Ultramarine Blue',
      'Lava Orange',
    ],
  },
  {
    brand: 'Army Painter',
    range: 'Fanatic Washes',
    paints: ['Dark Tone', 'Strong Tone', 'Soft Tone', 'Military Shader', 'Red Tone', 'Blue Tone'],
  },
  {
    brand: 'Army Painter',
    range: 'Speedpaint 2.0',
    paints: [
      'Wardog Brown',
      'Dragon Red',
      'Bloodveil Red',
      'Fanatic Blue',
      'Fangsblood Purple',
      'Ash Grey',
      'Herugrim Forest',
      'Goblin Green',
      'Zealot Yellow',
      'Sedna Skin',
    ],
  },
];
