export type BattlefieldRole = 'Epic Hero' | 'Character' | 'Battleline' | 'Infantry' | 'Mounted' | 'Vehicle' | 'Monster';

export const ROLE_ORDER: BattlefieldRole[] = [
  'Epic Hero',
  'Character',
  'Battleline',
  'Infantry',
  'Mounted',
  'Vehicle',
  'Monster',
];

export type CatalogUnit = { name: string; role: BattlefieldRole };

export const UNIT_CATALOG: Record<string, CatalogUnit[]> = {
  'Space Marines': [
    { name: 'Roboute Guilliman', role: 'Epic Hero' },
    { name: 'Captain', role: 'Character' },
    { name: 'Librarian', role: 'Character' },
    { name: 'Chaplain', role: 'Character' },
    { name: 'Intercessor Squad', role: 'Battleline' },
    { name: 'Assault Intercessors', role: 'Battleline' },
    { name: 'Terminator Squad', role: 'Infantry' },
    { name: 'Infiltrator Squad', role: 'Infantry' },
    { name: 'Eliminator Squad', role: 'Infantry' },
    { name: 'Aggressor Squad', role: 'Infantry' },
    { name: 'Scout Squad', role: 'Infantry' },
    { name: 'Devastator Squad', role: 'Infantry' },
    { name: 'Sternguard Veterans', role: 'Infantry' },
    { name: 'Vanguard Veterans', role: 'Infantry' },
    { name: 'Dreadnought', role: 'Vehicle' },
    { name: 'Redemptor Dreadnought', role: 'Vehicle' },
    { name: 'Rhino', role: 'Vehicle' },
    { name: 'Razorback', role: 'Vehicle' },
    { name: 'Impulsor', role: 'Vehicle' },
    { name: 'Repulsor', role: 'Vehicle' },
    { name: 'Land Raider', role: 'Vehicle' },
  ],
  'Astra Militarum': [
    { name: 'Commissar Yarrick', role: 'Epic Hero' },
    { name: 'Tank Commander', role: 'Character' },
    { name: 'Command Squad', role: 'Character' },
    { name: 'Infantry Squad', role: 'Battleline' },
    { name: 'Cadian Shock Troops', role: 'Battleline' },
    { name: 'Heavy Weapons Squad', role: 'Infantry' },
    { name: 'Kasrkin', role: 'Infantry' },
    { name: 'Bullgryns', role: 'Infantry' },
    { name: 'Ogryns', role: 'Infantry' },
    { name: 'Rough Riders', role: 'Mounted' },
    { name: 'Sentinel', role: 'Vehicle' },
    { name: 'Leman Russ Battle Tank', role: 'Vehicle' },
    { name: 'Chimera', role: 'Vehicle' },
    { name: 'Basilisk', role: 'Vehicle' },
    { name: 'Hellhound', role: 'Vehicle' },
    { name: 'Baneblade', role: 'Vehicle' },
  ],
  'Adeptus Mechanicus': [
    { name: 'Tech-Priest Dominus', role: 'Character' },
    { name: 'Skitarii Rangers', role: 'Battleline' },
    { name: 'Skitarii Vanguard', role: 'Battleline' },
    { name: 'Sicarian Infiltrators', role: 'Infantry' },
    { name: 'Sicarian Ruststalkers', role: 'Infantry' },
    { name: 'Kataphron Destroyers', role: 'Infantry' },
    { name: 'Kataphron Breachers', role: 'Infantry' },
    { name: 'Serberys Raiders', role: 'Mounted' },
    { name: 'Pteraxii Skystalkers', role: 'Infantry' },
    { name: 'Onager Dunecrawler', role: 'Vehicle' },
  ],
  'Adepta Sororitas': [
    { name: 'Saint Celestine', role: 'Epic Hero' },
    { name: 'Canoness', role: 'Character' },
    { name: 'Battle Sisters Squad', role: 'Battleline' },
    { name: 'Seraphim Squad', role: 'Infantry' },
    { name: 'Retributor Squad', role: 'Infantry' },
    { name: 'Dominion Squad', role: 'Infantry' },
    { name: 'Repentia Squad', role: 'Infantry' },
    { name: 'Zephyrim Squad', role: 'Infantry' },
    { name: 'Celestian Sacresants', role: 'Infantry' },
    { name: 'Immolator', role: 'Vehicle' },
    { name: 'Exorcist', role: 'Vehicle' },
  ],
  'Adeptus Custodes': [
    { name: 'Trajann Valoris', role: 'Epic Hero' },
    { name: 'Shield-Captain', role: 'Character' },
    { name: 'Custodian Guard', role: 'Battleline' },
    { name: 'Allarus Custodians', role: 'Infantry' },
    { name: 'Custodian Wardens', role: 'Infantry' },
    { name: 'Vertus Praetors', role: 'Mounted' },
    { name: 'Sagittarum Guard', role: 'Infantry' },
    { name: 'Venerable Contemptor Dreadnought', role: 'Vehicle' },
  ],
  'Grey Knights': [
    { name: 'Kaldor Draigo', role: 'Epic Hero' },
    { name: 'Brother-Captain', role: 'Character' },
    { name: 'Grand Master', role: 'Character' },
    { name: 'Strike Squad', role: 'Battleline' },
    { name: 'Terminator Squad', role: 'Infantry' },
    { name: 'Purifier Squad', role: 'Infantry' },
    { name: 'Interceptor Squad', role: 'Infantry' },
    { name: 'Purgation Squad', role: 'Infantry' },
    { name: 'Paladin Squad', role: 'Infantry' },
    { name: 'Nemesis Dreadknight', role: 'Vehicle' },
  ],
  'Imperial Knights': [
    { name: 'Knight Errant', role: 'Vehicle' },
    { name: 'Knight Paladin', role: 'Vehicle' },
    { name: 'Knight Warden', role: 'Vehicle' },
    { name: 'Knight Crusader', role: 'Vehicle' },
    { name: 'Knight Preceptor', role: 'Vehicle' },
    { name: 'Armiger Warglaive', role: 'Vehicle' },
    { name: 'Armiger Helverin', role: 'Vehicle' },
  ],
  'Agents of the Imperium': [
    { name: 'Inquisitor', role: 'Character' },
    { name: 'Culexus Assassin', role: 'Character' },
    { name: 'Callidus Assassin', role: 'Character' },
    { name: 'Eversor Assassin', role: 'Character' },
    { name: 'Vindicare Assassin', role: 'Character' },
    { name: 'Sisters of Silence Squad', role: 'Infantry' },
  ],
  'Chaos Space Marines': [
    { name: 'Abaddon the Despoiler', role: 'Epic Hero' },
    { name: 'Chaos Lord', role: 'Character' },
    { name: 'Sorcerer', role: 'Character' },
    { name: 'Warpsmith', role: 'Character' },
    { name: 'Chaos Space Marine Squad', role: 'Battleline' },
    { name: 'Chosen', role: 'Infantry' },
    { name: 'Terminator Squad', role: 'Infantry' },
    { name: 'Havocs', role: 'Infantry' },
    { name: 'Raptors', role: 'Mounted' },
    { name: 'Helbrute', role: 'Vehicle' },
    { name: 'Rhino', role: 'Vehicle' },
  ],
  'Death Guard': [
    { name: 'Mortarion', role: 'Epic Hero' },
    { name: 'Typhus', role: 'Epic Hero' },
    { name: 'Lord of Contagion', role: 'Character' },
    { name: 'Sorcerer', role: 'Character' },
    { name: 'Plague Marines', role: 'Battleline' },
    { name: 'Poxwalkers', role: 'Infantry' },
    { name: 'Blightlord Terminators', role: 'Infantry' },
    { name: 'Deathshroud Terminators', role: 'Infantry' },
    { name: 'Foetid Bloat-Drone', role: 'Vehicle' },
    { name: 'Myphitic Blight-Hauler', role: 'Vehicle' },
    { name: 'Plagueburst Crawler', role: 'Vehicle' },
  ],
  'Thousand Sons': [
    { name: 'Magnus the Red', role: 'Epic Hero' },
    { name: 'Ahriman', role: 'Epic Hero' },
    { name: 'Exalted Sorcerer', role: 'Character' },
    { name: 'Rubric Marines', role: 'Battleline' },
    { name: 'Scarab Occult Terminators', role: 'Infantry' },
    { name: 'Tzaangors', role: 'Infantry' },
    { name: 'Tzaangor Enlightened', role: 'Mounted' },
    { name: 'Helbrute', role: 'Vehicle' },
  ],
  'World Eaters': [
    { name: 'Angron', role: 'Epic Hero' },
    { name: "Khârn the Betrayer", role: 'Epic Hero' },
    { name: 'Lord Invocatus', role: 'Character' },
    { name: 'World Eaters Squad', role: 'Battleline' },
    { name: 'Khorne Berzerkers', role: 'Infantry' },
    { name: 'Jakhals', role: 'Infantry' },
    { name: 'Eightbound', role: 'Infantry' },
    { name: 'Exalted Eightbound', role: 'Infantry' },
  ],
  "Emperor's Children": [
    { name: 'Fabius Bile', role: 'Epic Hero' },
    { name: 'Chaos Lord', role: 'Character' },
    { name: "Emperor's Children Squad", role: 'Battleline' },
    { name: 'Noise Marines', role: 'Infantry' },
    { name: 'Infractors', role: 'Infantry' },
    { name: 'Kakophoni', role: 'Infantry' },
  ],
  'Chaos Daemons': [
    { name: 'Bloodletters', role: 'Battleline' },
    { name: 'Daemonettes', role: 'Battleline' },
    { name: 'Plaguebearers', role: 'Battleline' },
    { name: 'Pink Horrors', role: 'Battleline' },
    { name: 'Bloodthirster', role: 'Monster' },
    { name: 'Keeper of Secrets', role: 'Monster' },
    { name: 'Great Unclean One', role: 'Monster' },
    { name: 'Lord of Change', role: 'Monster' },
  ],
  'Chaos Knights': [
    { name: 'Knight Rampager', role: 'Vehicle' },
    { name: 'Knight Tyrant', role: 'Vehicle' },
    { name: 'Knight Despoiler', role: 'Vehicle' },
    { name: 'Knight Abominant', role: 'Vehicle' },
    { name: 'War Dog Executioner', role: 'Vehicle' },
  ],
  Orks: [
    { name: 'Ghazghkull Thraka', role: 'Epic Hero' },
    { name: 'Wazdakka Gutsmek', role: 'Epic Hero' },
    { name: 'Warboss', role: 'Character' },
    { name: 'Weirdboy', role: 'Character' },
    { name: 'Boyz', role: 'Battleline' },
    { name: 'Gretchin', role: 'Battleline' },
    { name: 'Nobz', role: 'Infantry' },
    { name: 'Meganobz', role: 'Infantry' },
    { name: 'Kommandos', role: 'Infantry' },
    { name: 'Stormboyz', role: 'Mounted' },
    { name: 'Killa Kans', role: 'Vehicle' },
    { name: 'Gorkanaut', role: 'Vehicle' },
    { name: 'Trukk', role: 'Vehicle' },
    { name: 'Battlewagon', role: 'Vehicle' },
    { name: 'Deffkopta', role: 'Mounted' },
  ],
  Necrons: [
    { name: 'Imotekh the Stormlord', role: 'Epic Hero' },
    { name: 'Overlord', role: 'Character' },
    { name: 'Necron Warriors', role: 'Battleline' },
    { name: 'Immortals', role: 'Battleline' },
    { name: 'Lychguard', role: 'Infantry' },
    { name: 'Triarch Praetorians', role: 'Infantry' },
    { name: 'Deathmarks', role: 'Infantry' },
    { name: 'Flayed Ones', role: 'Infantry' },
    { name: 'Skorpekh Destroyers', role: 'Infantry' },
    { name: 'Destroyers', role: 'Mounted' },
    { name: 'Canoptek Wraiths', role: 'Monster' },
    { name: 'Canoptek Scarabs', role: 'Infantry' },
    { name: 'Doomstalker', role: 'Vehicle' },
  ],
  Tyranids: [
    { name: 'The Swarmlord', role: 'Epic Hero' },
    { name: 'Hive Tyrant', role: 'Character' },
    { name: 'Broodlord', role: 'Character' },
    { name: 'Termagants', role: 'Battleline' },
    { name: 'Hormagaunts', role: 'Battleline' },
    { name: 'Genestealers', role: 'Infantry' },
    { name: 'Tyranid Warriors', role: 'Infantry' },
    { name: 'Ravener Brood', role: 'Mounted' },
    { name: 'Zoanthropes', role: 'Infantry' },
    { name: 'Carnifex', role: 'Monster' },
    { name: 'Tervigon', role: 'Monster' },
    { name: 'Trygon', role: 'Monster' },
  ],
  Aeldari: [
    { name: 'Eldrad Ulthran', role: 'Epic Hero' },
    { name: 'Farseer', role: 'Character' },
    { name: 'Autarch', role: 'Character' },
    { name: 'Guardian Defenders', role: 'Battleline' },
    { name: 'Dire Avengers', role: 'Infantry' },
    { name: 'Howling Banshees', role: 'Infantry' },
    { name: 'Striking Scorpions', role: 'Infantry' },
    { name: 'Fire Dragons', role: 'Infantry' },
    { name: 'Wraithguard', role: 'Infantry' },
    { name: 'Wraithblades', role: 'Infantry' },
    { name: 'Wave Serpent', role: 'Vehicle' },
    { name: 'Falcon', role: 'Vehicle' },
  ],
  Drukhari: [
    { name: 'Lelith Hesperax', role: 'Epic Hero' },
    { name: 'Archon', role: 'Character' },
    { name: 'Succubus', role: 'Character' },
    { name: 'Kabalite Warriors', role: 'Battleline' },
    { name: 'Wyches', role: 'Infantry' },
    { name: 'Incubi', role: 'Infantry' },
    { name: 'Mandrakes', role: 'Infantry' },
    { name: 'Wracks', role: 'Infantry' },
    { name: 'Grotesques', role: 'Infantry' },
    { name: 'Scourges', role: 'Infantry' },
    { name: 'Reavers', role: 'Mounted' },
    { name: 'Raider', role: 'Vehicle' },
    { name: 'Venom', role: 'Vehicle' },
  ],
  'Tau Empire': [
    { name: 'Commander Farsight', role: 'Epic Hero' },
    { name: 'Ethereal', role: 'Character' },
    { name: 'Fire Warriors', role: 'Battleline' },
    { name: 'Breacher Team', role: 'Battleline' },
    { name: 'Strike Team', role: 'Battleline' },
    { name: 'Pathfinders', role: 'Infantry' },
    { name: 'Crisis Battlesuits', role: 'Infantry' },
    { name: 'Stealth Battlesuits', role: 'Infantry' },
    { name: 'Broadside Battlesuits', role: 'Infantry' },
    { name: 'Riptide Battlesuit', role: 'Monster' },
    { name: 'Devilfish', role: 'Vehicle' },
    { name: 'Hammerhead Gunship', role: 'Vehicle' },
  ],
  'Genestealer Cults': [
    { name: 'Primus', role: 'Character' },
    { name: 'Magus', role: 'Character' },
    { name: 'Patriarch', role: 'Epic Hero' },
    { name: 'Neophyte Hybrids', role: 'Battleline' },
    { name: 'Acolyte Hybrids', role: 'Infantry' },
    { name: 'Purestrain Genestealers', role: 'Infantry' },
    { name: 'Aberrants', role: 'Infantry' },
    { name: 'Metamorphs', role: 'Infantry' },
    { name: 'Goliath Truck', role: 'Vehicle' },
  ],
  'Leagues of Votann': [
    { name: 'Pioneer Sergeant', role: 'Character' },
    { name: 'Hearthkyn Warriors', role: 'Battleline' },
    { name: 'Hernkyn Yaegirs', role: 'Mounted' },
    { name: 'Einhyr Champions', role: 'Infantry' },
    { name: 'Brôkhyr Thunderkyn', role: 'Infantry' },
    { name: 'Cthonian Beserks', role: 'Infantry' },
    { name: 'Hekaton Land Fortress', role: 'Vehicle' },
  ],
};

// Chapter-specific troops, shown alongside the generic Space Marines list
// when that chapter is selected.
export const CHAPTER_UNIT_CATALOG: Record<string, CatalogUnit[]> = {
  'Blood Angels': [
    { name: 'The Sanguinor', role: 'Epic Hero' },
    { name: 'Commander Dante', role: 'Epic Hero' },
    { name: 'Mephiston, Lord of Death', role: 'Epic Hero' },
    { name: 'Sanguinary Priest', role: 'Character' },
    { name: 'Sanguinary Ancient', role: 'Character' },
    { name: 'Death Company', role: 'Infantry' },
    { name: 'Sanguinary Guard', role: 'Infantry' },
    { name: 'Death Company Dreadnought', role: 'Vehicle' },
    { name: 'Baal Predator', role: 'Vehicle' },
  ],
  'Dark Angels': [
    { name: 'Azrael', role: 'Epic Hero' },
    { name: 'Belial', role: 'Epic Hero' },
    { name: 'Interrogator-Chaplain', role: 'Character' },
    { name: 'Ezekiel', role: 'Character' },
    { name: 'Deathwing Knights', role: 'Infantry' },
    { name: 'Deathwing Terminator Squad', role: 'Infantry' },
    { name: 'Ravenwing Black Knights', role: 'Mounted' },
    { name: 'Ravenwing Bike Squad', role: 'Mounted' },
  ],
  'Space Wolves': [
    { name: 'Logan Grimnar', role: 'Epic Hero' },
    { name: 'Ragnar Blackmane', role: 'Epic Hero' },
    { name: 'Njal Stormcaller', role: 'Epic Hero' },
    { name: 'Iron Priest', role: 'Character' },
    { name: 'Lone Wolf', role: 'Character' },
    { name: 'Wulfen', role: 'Infantry' },
    { name: 'Wolf Guard Terminators', role: 'Infantry' },
    { name: 'Thunderwolf Cavalry', role: 'Mounted' },
  ],
  'Black Templars': [
    { name: 'High Marshal Helbrecht', role: 'Epic Hero' },
    { name: 'Marshal Grimaldus', role: 'Epic Hero' },
    { name: "Emperor's Champion", role: 'Character' },
    { name: 'Castellan', role: 'Character' },
    { name: 'Sword Brethren', role: 'Infantry' },
    { name: 'Primaris Crusader Squad', role: 'Battleline' },
  ],
  Deathwatch: [
    { name: 'Watch Master', role: 'Epic Hero' },
    { name: 'Watch Captain', role: 'Character' },
    { name: 'Deathwatch Veterans', role: 'Infantry' },
    { name: 'Deathwatch Kill Team', role: 'Infantry' },
  ],
};
