export const UNIT_CATALOG: Record<string, string[]> = {
  'Space Marines': [
    'Intercessor Squad',
    'Assault Intercessors',
    'Terminator Squad',
    'Infiltrator Squad',
    'Eliminator Squad',
    'Aggressor Squad',
    'Scout Squad',
    'Devastator Squad',
    'Sternguard Veterans',
    'Vanguard Veterans',
    'Captain',
    'Librarian',
    'Chaplain',
    'Dreadnought',
    'Redemptor Dreadnought',
    'Rhino',
    'Razorback',
    'Impulsor',
    'Repulsor',
    'Land Raider',
  ],
  'Astra Militarum': [
    'Infantry Squad',
    'Cadian Shock Troops',
    'Heavy Weapons Squad',
    'Command Squad',
    'Kasrkin',
    'Bullgryns',
    'Ogryns',
    'Rough Riders',
    'Sentinel',
    'Tank Commander',
    'Leman Russ Battle Tank',
    'Chimera',
    'Basilisk',
    'Hellhound',
    'Baneblade',
  ],
  'Adeptus Mechanicus': [
    'Skitarii Rangers',
    'Skitarii Vanguard',
    'Sicarian Infiltrators',
    'Sicarian Ruststalkers',
    'Kataphron Destroyers',
    'Kataphron Breachers',
    'Serberys Raiders',
    'Pteraxii Skystalkers',
    'Tech-Priest Dominus',
    'Onager Dunecrawler',
  ],
  'Adepta Sororitas': [
    'Battle Sisters Squad',
    'Seraphim Squad',
    'Retributor Squad',
    'Dominion Squad',
    'Repentia Squad',
    'Zephyrim Squad',
    'Celestian Sacresants',
    'Canoness',
    'Immolator',
    'Exorcist',
  ],
  'Adeptus Custodes': [
    'Custodian Guard',
    'Allarus Custodians',
    'Custodian Wardens',
    'Vertus Praetors',
    'Sagittarum Guard',
    'Shield-Captain',
    'Venerable Contemptor Dreadnought',
  ],
  'Grey Knights': [
    'Strike Squad',
    'Terminator Squad',
    'Purifier Squad',
    'Interceptor Squad',
    'Purgation Squad',
    'Paladin Squad',
    'Brother-Captain',
    'Grand Master',
    'Nemesis Dreadknight',
  ],
  'Imperial Knights': [
    'Knight Errant',
    'Knight Paladin',
    'Knight Warden',
    'Knight Crusader',
    'Knight Preceptor',
    'Armiger Warglaive',
    'Armiger Helverin',
  ],
  'Agents of the Imperium': [
    'Inquisitor',
    'Culexus Assassin',
    'Callidus Assassin',
    'Eversor Assassin',
    'Vindicare Assassin',
    'Sisters of Silence Squad',
  ],
  'Chaos Space Marines': [
    'Chaos Space Marine Squad',
    'Chosen',
    'Terminator Squad',
    'Havocs',
    'Raptors',
    'Chaos Lord',
    'Sorcerer',
    'Warpsmith',
    'Helbrute',
    'Rhino',
  ],
  'Death Guard': [
    'Plague Marines',
    'Poxwalkers',
    'Blightlord Terminators',
    'Deathshroud Terminators',
    'Foetid Bloat-Drone',
    'Myphitic Blight-Hauler',
    'Lord of Contagion',
    'Sorcerer',
    'Plagueburst Crawler',
  ],
  'Thousand Sons': [
    'Rubric Marines',
    'Scarab Occult Terminators',
    'Tzaangors',
    'Tzaangor Enlightened',
    'Exalted Sorcerer',
    'Ahriman',
    'Helbrute',
  ],
  'World Eaters': [
    'World Eaters Squad',
    'Khorne Berzerkers',
    'Jakhals',
    'Eightbound',
    'Exalted Eightbound',
    'Angron',
    'Lord Invocatus',
  ],
  "Emperor's Children": ['Noise Marines', "Emperor's Children Squad", 'Infractors', 'Kakophoni', 'Fabius Bile', 'Chaos Lord'],
  'Chaos Daemons': [
    'Bloodletters',
    'Daemonettes',
    'Plaguebearers',
    'Pink Horrors',
    'Bloodthirster',
    'Keeper of Secrets',
    'Great Unclean One',
    'Lord of Change',
  ],
  'Chaos Knights': ['Knight Rampager', 'Knight Tyrant', 'Knight Despoiler', 'Knight Abominant', 'War Dog Executioner'],
  Orks: [
    'Boyz',
    'Nobz',
    'Meganobz',
    'Gretchin',
    'Kommandos',
    'Stormboyz',
    'Warboss',
    'Weirdboy',
    'Killa Kans',
    'Gorkanaut',
    'Trukk',
    'Battlewagon',
    'Deffkopta',
  ],
  Necrons: [
    'Necron Warriors',
    'Immortals',
    'Lychguard',
    'Triarch Praetorians',
    'Deathmarks',
    'Flayed Ones',
    'Canoptek Wraiths',
    'Canoptek Scarabs',
    'Skorpekh Destroyers',
    'Destroyers',
    'Overlord',
    'Doomstalker',
  ],
  Tyranids: [
    'Termagants',
    'Hormagaunts',
    'Genestealers',
    'Tyranid Warriors',
    'Ravener Brood',
    'Carnifex',
    'Tervigon',
    'Zoanthropes',
    'Broodlord',
    'Hive Tyrant',
    'Trygon',
  ],
  Aeldari: [
    'Guardian Defenders',
    'Dire Avengers',
    'Howling Banshees',
    'Striking Scorpions',
    'Fire Dragons',
    'Wraithguard',
    'Wraithblades',
    'Farseer',
    'Autarch',
    'Wave Serpent',
    'Falcon',
  ],
  Drukhari: [
    'Kabalite Warriors',
    'Wyches',
    'Incubi',
    'Mandrakes',
    'Wracks',
    'Grotesques',
    'Scourges',
    'Reavers',
    'Archon',
    'Succubus',
    'Raider',
    'Venom',
  ],
  'Tau Empire': [
    'Fire Warriors',
    'Breacher Team',
    'Strike Team',
    'Pathfinders',
    'Crisis Battlesuits',
    'Stealth Battlesuits',
    'Riptide Battlesuit',
    'Broadside Battlesuits',
    'Ethereal',
    'Devilfish',
    'Hammerhead Gunship',
  ],
  'Genestealer Cults': [
    'Neophyte Hybrids',
    'Acolyte Hybrids',
    'Purestrain Genestealers',
    'Aberrants',
    'Metamorphs',
    'Primus',
    'Magus',
    'Patriarch',
    'Goliath Truck',
  ],
  'Leagues of Votann': [
    'Hearthkyn Warriors',
    'Hernkyn Yaegirs',
    'Einhyr Champions',
    'Pioneer Sergeant',
    'Brôkhyr Thunderkyn',
    'Cthonian Beserks',
    'Hekaton Land Fortress',
  ],
};
