export type BattlefieldRole = 'Epic Hero' | 'Character' | 'Battleline' | 'Infantry' | 'Mounted' | 'Vehicle' | 'Monster';

export const ROLE_ORDER: BattlefieldRole[] = [
  'Epic Hero',
  'Character',
  'Battleline',
  'Infantry',
  'Mounted',
  'Vehicle',
  'Monster',
];

export type CatalogUnit = { name: string; role: BattlefieldRole };

export const UNIT_CATALOG: Record<string, CatalogUnit[]> = {
  'Space Marines': [
    { name: 'Roboute Guilliman', role: 'Epic Hero' },
    { name: 'Marneus Calgar', role: 'Epic Hero' },
    { name: 'Captain', role: 'Character' },
    { name: 'Librarian', role: 'Character' },
    { name: 'Chaplain', role: 'Character' },
    { name: 'Lieutenant', role: 'Character' },
    { name: 'Techmarine', role: 'Character' },
    { name: 'Apothecary', role: 'Character' },
    { name: 'Ancient', role: 'Character' },
    { name: 'Intercessor Squad', role: 'Battleline' },
    { name: 'Assault Intercessors', role: 'Battleline' },
    { name: 'Tactical Squad', role: 'Battleline' },
    { name: 'Terminator Squad', role: 'Infantry' },
    { name: 'Infiltrator Squad', role: 'Infantry' },
    { name: 'Eliminator Squad', role: 'Infantry' },
    { name: 'Aggressor Squad', role: 'Infantry' },
    { name: 'Scout Squad', role: 'Infantry' },
    { name: 'Devastator Squad', role: 'Infantry' },
    { name: 'Sternguard Veterans', role: 'Infantry' },
    { name: 'Vanguard Veterans', role: 'Infantry' },
    { name: 'Incursor Squad', role: 'Infantry' },
    { name: 'Suppressor Squad', role: 'Infantry' },
    { name: 'Bladeguard Veterans', role: 'Infantry' },
    { name: 'Company Heroes', role: 'Infantry' },
    { name: 'Bike Squad', role: 'Mounted' },
    { name: 'Outrider Squad', role: 'Mounted' },
    { name: 'Dreadnought', role: 'Vehicle' },
    { name: 'Redemptor Dreadnought', role: 'Vehicle' },
    { name: 'Rhino', role: 'Vehicle' },
    { name: 'Razorback', role: 'Vehicle' },
    { name: 'Impulsor', role: 'Vehicle' },
    { name: 'Repulsor', role: 'Vehicle' },
    { name: 'Repulsor Executioner', role: 'Vehicle' },
    { name: 'Land Raider', role: 'Vehicle' },
    { name: 'Land Speeder', role: 'Vehicle' },
    { name: 'Predator', role: 'Vehicle' },
    { name: 'Vindicator', role: 'Vehicle' },
    { name: 'Whirlwind', role: 'Vehicle' },
    { name: 'Stormraven Gunship', role: 'Vehicle' },
    { name: 'Storm Speeder', role: 'Vehicle' },
  ],
  'Astra Militarum': [
    { name: 'Commissar Yarrick', role: 'Epic Hero' },
    { name: 'Lord Solar Leontus', role: 'Epic Hero' },
    { name: 'Tank Commander', role: 'Character' },
    { name: 'Company Commander', role: 'Character' },
    { name: 'Command Squad', role: 'Character' },
    { name: 'Primaris Psyker', role: 'Character' },
    { name: 'Ministorum Priest', role: 'Character' },
    { name: 'Infantry Squad', role: 'Battleline' },
    { name: 'Cadian Shock Troops', role: 'Battleline' },
    { name: 'Heavy Weapons Squad', role: 'Infantry' },
    { name: 'Kasrkin', role: 'Infantry' },
    { name: 'Bullgryns', role: 'Infantry' },
    { name: 'Ogryns', role: 'Infantry' },
    { name: 'Ratlings', role: 'Infantry' },
    { name: 'Militarum Tempestus Scions', role: 'Infantry' },
    { name: 'Rough Riders', role: 'Mounted' },
    { name: 'Attilan Rough Riders', role: 'Mounted' },
    { name: 'Sentinel', role: 'Vehicle' },
    { name: 'Leman Russ Battle Tank', role: 'Vehicle' },
    { name: 'Chimera', role: 'Vehicle' },
    { name: 'Basilisk', role: 'Vehicle' },
    { name: 'Hellhound', role: 'Vehicle' },
    { name: 'Wyvern', role: 'Vehicle' },
    { name: 'Manticore', role: 'Vehicle' },
    { name: 'Hydra', role: 'Vehicle' },
    { name: 'Deathstrike', role: 'Vehicle' },
    { name: 'Baneblade', role: 'Vehicle' },
  ],
  'Adeptus Mechanicus': [
    { name: 'Belisarius Cawl', role: 'Epic Hero' },
    { name: 'Tech-Priest Dominus', role: 'Character' },
    { name: 'Tech-Priest Manipulus', role: 'Character' },
    { name: 'Cybernetica Datasmith', role: 'Character' },
    { name: 'Skitarii Rangers', role: 'Battleline' },
    { name: 'Skitarii Vanguard', role: 'Battleline' },
    { name: 'Sicarian Infiltrators', role: 'Infantry' },
    { name: 'Sicarian Ruststalkers', role: 'Infantry' },
    { name: 'Kataphron Destroyers', role: 'Infantry' },
    { name: 'Kataphron Breachers', role: 'Infantry' },
    { name: 'Pteraxii Skystalkers', role: 'Infantry' },
    { name: 'Corpuscarii Electro-Priests', role: 'Infantry' },
    { name: 'Fulgurite Electro-Priests', role: 'Infantry' },
    { name: 'Serberys Raiders', role: 'Mounted' },
    { name: 'Serberys Sulphurhounds', role: 'Mounted' },
    { name: 'Onager Dunecrawler', role: 'Vehicle' },
    { name: 'Kastelan Robots', role: 'Vehicle' },
    { name: 'Skorpius Dunerider', role: 'Vehicle' },
    { name: 'Skorpius Disintegrator', role: 'Vehicle' },
  ],
  'Adepta Sororitas': [
    { name: 'Saint Celestine', role: 'Epic Hero' },
    { name: 'Canoness', role: 'Character' },
    { name: 'Palatine', role: 'Character' },
    { name: 'Ministorum Priest', role: 'Character' },
    { name: 'Missionary', role: 'Character' },
    { name: 'Battle Sisters Squad', role: 'Battleline' },
    { name: 'Seraphim Squad', role: 'Infantry' },
    { name: 'Retributor Squad', role: 'Infantry' },
    { name: 'Dominion Squad', role: 'Infantry' },
    { name: 'Repentia Squad', role: 'Infantry' },
    { name: 'Zephyrim Squad', role: 'Infantry' },
    { name: 'Celestian Sacresants', role: 'Infantry' },
    { name: 'Arco-flagellants', role: 'Infantry' },
    { name: 'Death Cult Assassins', role: 'Infantry' },
    { name: 'Immolator', role: 'Vehicle' },
    { name: 'Exorcist', role: 'Vehicle' },
    { name: 'Castigator', role: 'Vehicle' },
    { name: 'Penitent Engine', role: 'Vehicle' },
  ],
  'Adeptus Custodes': [
    { name: 'Trajann Valoris', role: 'Epic Hero' },
    { name: 'Valerian', role: 'Epic Hero' },
    { name: 'Shield-Captain', role: 'Character' },
    { name: 'Blade Champion', role: 'Character' },
    { name: 'Custodian Guard', role: 'Battleline' },
    { name: 'Allarus Custodians', role: 'Infantry' },
    { name: 'Custodian Wardens', role: 'Infantry' },
    { name: 'Sagittarum Guard', role: 'Infantry' },
    { name: 'Vertus Praetors', role: 'Mounted' },
    { name: 'Venerable Contemptor Dreadnought', role: 'Vehicle' },
    { name: 'Coronus Grav-carrier', role: 'Vehicle' },
    { name: 'Orion Assault Dropship', role: 'Vehicle' },
  ],
  'Grey Knights': [
    { name: 'Kaldor Draigo', role: 'Epic Hero' },
    { name: 'Brother-Captain', role: 'Character' },
    { name: 'Grand Master', role: 'Character' },
    { name: 'Techmarine', role: 'Character' },
    { name: 'Librarian', role: 'Character' },
    { name: 'Strike Squad', role: 'Battleline' },
    { name: 'Terminator Squad', role: 'Infantry' },
    { name: 'Purifier Squad', role: 'Infantry' },
    { name: 'Interceptor Squad', role: 'Infantry' },
    { name: 'Purgation Squad', role: 'Infantry' },
    { name: 'Paladin Squad', role: 'Infantry' },
    { name: 'Nemesis Dreadknight', role: 'Vehicle' },
    { name: 'Land Raider', role: 'Vehicle' },
    { name: 'Razorback', role: 'Vehicle' },
  ],
  'Imperial Knights': [
    { name: 'Canis Rex', role: 'Epic Hero' },
    { name: 'Knight Errant', role: 'Vehicle' },
    { name: 'Knight Paladin', role: 'Vehicle' },
    { name: 'Knight Warden', role: 'Vehicle' },
    { name: 'Knight Crusader', role: 'Vehicle' },
    { name: 'Knight Preceptor', role: 'Vehicle' },
    { name: 'Knight Gallant', role: 'Vehicle' },
    { name: 'Knight Castellan', role: 'Vehicle' },
    { name: 'Armiger Warglaive', role: 'Vehicle' },
    { name: 'Armiger Helverin', role: 'Vehicle' },
  ],
  'Agents of the Imperium': [
    { name: 'Inquisitor', role: 'Character' },
    { name: 'Culexus Assassin', role: 'Character' },
    { name: 'Callidus Assassin', role: 'Character' },
    { name: 'Eversor Assassin', role: 'Character' },
    { name: 'Vindicare Assassin', role: 'Character' },
    { name: 'Sisters of Silence Squad', role: 'Infantry' },
    { name: 'Crusaders', role: 'Infantry' },
  ],
  'Chaos Space Marines': [
    { name: 'Abaddon the Despoiler', role: 'Epic Hero' },
    { name: 'Haarken Worldclaimer', role: 'Epic Hero' },
    { name: 'Chaos Lord', role: 'Character' },
    { name: 'Sorcerer', role: 'Character' },
    { name: 'Warpsmith', role: 'Character' },
    { name: 'Master of Possession', role: 'Character' },
    { name: 'Dark Apostle', role: 'Character' },
    { name: 'Exalted Champion', role: 'Character' },
    { name: 'Chaos Space Marine Squad', role: 'Battleline' },
    { name: 'Legionaries', role: 'Battleline' },
    { name: 'Chosen', role: 'Infantry' },
    { name: 'Terminator Squad', role: 'Infantry' },
    { name: 'Havocs', role: 'Infantry' },
    { name: 'Cultist Mob', role: 'Infantry' },
    { name: 'Possessed', role: 'Infantry' },
    { name: 'Raptors', role: 'Mounted' },
    { name: 'Warp Talons', role: 'Mounted' },
    { name: 'Chaos Bikers', role: 'Mounted' },
    { name: 'Helbrute', role: 'Vehicle' },
    { name: 'Rhino', role: 'Vehicle' },
    { name: 'Chaos Land Raider', role: 'Vehicle' },
    { name: 'Predator', role: 'Vehicle' },
    { name: 'Vindicator', role: 'Vehicle' },
    { name: 'Chaos Land Speeder', role: 'Vehicle' },
  ],
  'Death Guard': [
    { name: 'Mortarion', role: 'Epic Hero' },
    { name: 'Typhus', role: 'Epic Hero' },
    { name: 'Lord of Contagion', role: 'Character' },
    { name: 'Sorcerer', role: 'Character' },
    { name: 'Biologus Putrifier', role: 'Character' },
    { name: 'Noxious Blightbringer', role: 'Character' },
    { name: 'Plague Marines', role: 'Battleline' },
    { name: 'Poxwalkers', role: 'Infantry' },
    { name: 'Blightlord Terminators', role: 'Infantry' },
    { name: 'Deathshroud Terminators', role: 'Infantry' },
    { name: 'Nurglings', role: 'Infantry' },
    { name: 'Foetid Bloat-Drone', role: 'Vehicle' },
    { name: 'Myphitic Blight-Hauler', role: 'Vehicle' },
    { name: 'Plagueburst Crawler', role: 'Vehicle' },
    { name: 'Foetid Blight Drone', role: 'Vehicle' },
  ],
  'Thousand Sons': [
    { name: 'Magnus the Red', role: 'Epic Hero' },
    { name: 'Ahriman', role: 'Epic Hero' },
    { name: 'Exalted Sorcerer', role: 'Character' },
    { name: 'Infernal Master', role: 'Character' },
    { name: 'Rubric Marines', role: 'Battleline' },
    { name: 'Scarab Occult Terminators', role: 'Infantry' },
    { name: 'Tzaangors', role: 'Infantry' },
    { name: 'Tzaangor Shamans', role: 'Infantry' },
    { name: 'Tzaangor Enlightened', role: 'Mounted' },
    { name: 'Helbrute', role: 'Vehicle' },
    { name: 'Chaos Land Raider', role: 'Vehicle' },
  ],
  'World Eaters': [
    { name: 'Angron', role: 'Epic Hero' },
    { name: "Khârn the Betrayer", role: 'Epic Hero' },
    { name: 'Lord Invocatus', role: 'Character' },
    { name: 'Master of Executions', role: 'Character' },
    { name: 'World Eaters Squad', role: 'Battleline' },
    { name: 'Khorne Berzerkers', role: 'Infantry' },
    { name: 'Jakhals', role: 'Infantry' },
    { name: 'Eightbound', role: 'Infantry' },
    { name: 'Exalted Eightbound', role: 'Infantry' },
  ],
  "Emperor's Children": [
    { name: 'Fabius Bile', role: 'Epic Hero' },
    { name: 'Lucius the Eternal', role: 'Epic Hero' },
    { name: 'Chaos Lord', role: 'Character' },
    { name: "Emperor's Children Squad", role: 'Battleline' },
    { name: 'Noise Marines', role: 'Infantry' },
    { name: 'Infractors', role: 'Infantry' },
    { name: 'Kakophoni', role: 'Infantry' },
    { name: 'Palatine Blades', role: 'Infantry' },
  ],
  'Chaos Daemons': [
    { name: 'Skarbrand', role: 'Epic Hero' },
    { name: "Kairos Fateweaver", role: 'Epic Hero' },
    { name: 'Bloodletters', role: 'Battleline' },
    { name: 'Daemonettes', role: 'Battleline' },
    { name: 'Plaguebearers', role: 'Battleline' },
    { name: 'Pink Horrors', role: 'Battleline' },
    { name: 'Flesh Hounds', role: 'Infantry' },
    { name: 'Seekers of Slaanesh', role: 'Infantry' },
    { name: 'Blue Horrors', role: 'Infantry' },
    { name: 'Beasts of Nurgle', role: 'Mounted' },
    { name: 'Fiends of Slaanesh', role: 'Mounted' },
    { name: 'Flamers of Tzeentch', role: 'Mounted' },
    { name: 'Bloodthirster', role: 'Monster' },
    { name: 'Keeper of Secrets', role: 'Monster' },
    { name: 'Great Unclean One', role: 'Monster' },
    { name: 'Lord of Change', role: 'Monster' },
    { name: 'Soul Grinder', role: 'Monster' },
  ],
  'Chaos Knights': [
    { name: 'Knight Rampager', role: 'Vehicle' },
    { name: 'Knight Tyrant', role: 'Vehicle' },
    { name: 'Knight Despoiler', role: 'Vehicle' },
    { name: 'Knight Abominant', role: 'Vehicle' },
    { name: 'Knight Desecrator', role: 'Vehicle' },
    { name: 'War Dog Executioner', role: 'Vehicle' },
    { name: 'War Dog Brigand', role: 'Vehicle' },
  ],
  Orks: [
    { name: 'Ghazghkull Thraka', role: 'Epic Hero' },
    { name: 'Wazdakka Gutsmek', role: 'Epic Hero' },
    { name: 'Warboss', role: 'Character' },
    { name: 'Weirdboy', role: 'Character' },
    { name: 'Big Mek', role: 'Character' },
    { name: 'Painboy', role: 'Character' },
    { name: 'Boyz', role: 'Battleline' },
    { name: 'Gretchin', role: 'Battleline' },
    { name: 'Nobz', role: 'Infantry' },
    { name: 'Meganobz', role: 'Infantry' },
    { name: 'Kommandos', role: 'Infantry' },
    { name: 'Tankbustas', role: 'Infantry' },
    { name: 'Burna Boyz', role: 'Infantry' },
    { name: 'Lootas', role: 'Infantry' },
    { name: 'Stormboyz', role: 'Mounted' },
    { name: 'Deffkopta', role: 'Mounted' },
    { name: 'Warbikers', role: 'Mounted' },
    { name: 'Killa Kans', role: 'Vehicle' },
    { name: 'Gorkanaut', role: 'Vehicle' },
    { name: 'Morkanaut', role: 'Vehicle' },
    { name: 'Trukk', role: 'Vehicle' },
    { name: 'Battlewagon', role: 'Vehicle' },
    { name: 'Deff Dread', role: 'Vehicle' },
  ],
  Necrons: [
    { name: 'Imotekh the Stormlord', role: 'Epic Hero' },
    { name: 'The Silent King', role: 'Epic Hero' },
    { name: 'Overlord', role: 'Character' },
    { name: 'Cryptek', role: 'Character' },
    { name: 'Royal Warden', role: 'Character' },
    { name: 'Necron Warriors', role: 'Battleline' },
    { name: 'Immortals', role: 'Battleline' },
    { name: 'Lychguard', role: 'Infantry' },
    { name: 'Triarch Praetorians', role: 'Infantry' },
    { name: 'Deathmarks', role: 'Infantry' },
    { name: 'Flayed Ones', role: 'Infantry' },
    { name: 'Skorpekh Destroyers', role: 'Infantry' },
    { name: 'Lokhust Heavy Destroyers', role: 'Infantry' },
    { name: 'Destroyers', role: 'Mounted' },
    { name: 'Canoptek Wraiths', role: 'Mounted' },
    { name: 'Canoptek Scarabs', role: 'Infantry' },
    { name: 'Canoptek Doomstalker', role: 'Monster' },
    { name: 'Ophydian Destroyer', role: 'Monster' },
    { name: 'Ghost Ark', role: 'Vehicle' },
    { name: 'Doomsday Ark', role: 'Vehicle' },
    { name: 'Monolith', role: 'Vehicle' },
  ],
  Tyranids: [
    { name: 'The Swarmlord', role: 'Epic Hero' },
    { name: 'Old One Eye', role: 'Epic Hero' },
    { name: 'The Deathleaper', role: 'Epic Hero' },
    { name: 'Hive Tyrant', role: 'Character' },
    { name: 'Winged Hive Tyrant', role: 'Character' },
    { name: 'Broodlord', role: 'Character' },
    { name: 'Neurotyrant', role: 'Character' },
    { name: 'Prime', role: 'Character' },
    { name: 'Termagants', role: 'Battleline' },
    { name: 'Hormagaunts', role: 'Battleline' },
    { name: 'Genestealers', role: 'Infantry' },
    { name: 'Tyranid Warriors', role: 'Infantry' },
    { name: 'Neurogaunts', role: 'Infantry' },
    { name: 'Ripper Swarms', role: 'Infantry' },
    { name: 'Pyrovores', role: 'Infantry' },
    { name: 'Venomthropes', role: 'Infantry' },
    { name: 'Barbgaunts', role: 'Infantry' },
    { name: 'Zoanthropes', role: 'Infantry' },
    { name: 'Ravener Brood', role: 'Mounted' },
    { name: "Von Ryan's Leapers", role: 'Mounted' },
    { name: 'Carnifex', role: 'Monster' },
    { name: 'Tervigon', role: 'Monster' },
    { name: 'Trygon', role: 'Monster' },
    { name: 'Exocrine', role: 'Monster' },
    { name: 'Haruspex', role: 'Monster' },
    { name: 'Maleceptor', role: 'Monster' },
    { name: 'Tyrannofex', role: 'Monster' },
    { name: 'Toxicrene', role: 'Monster' },
    { name: 'Screamer-Killer', role: 'Monster' },
    { name: 'Psychophage', role: 'Monster' },
    { name: 'Norn Emissary', role: 'Monster' },
    { name: 'Harpy', role: 'Monster' },
    { name: 'Hive Crone', role: 'Monster' },
    { name: 'Sporocyst', role: 'Monster' },
  ],
  Aeldari: [
    { name: 'Eldrad Ulthran', role: 'Epic Hero' },
    { name: 'Yvraine', role: 'Epic Hero' },
    { name: 'The Yncarne', role: 'Epic Hero' },
    { name: 'Farseer', role: 'Character' },
    { name: 'Autarch', role: 'Character' },
    { name: 'Spiritseer', role: 'Character' },
    { name: 'Warlock', role: 'Character' },
    { name: 'Guardian Defenders', role: 'Battleline' },
    { name: 'Dire Avengers', role: 'Infantry' },
    { name: 'Howling Banshees', role: 'Infantry' },
    { name: 'Striking Scorpions', role: 'Infantry' },
    { name: 'Fire Dragons', role: 'Infantry' },
    { name: 'Wraithguard', role: 'Infantry' },
    { name: 'Wraithblades', role: 'Infantry' },
    { name: 'Rangers', role: 'Infantry' },
    { name: 'Shining Spears', role: 'Mounted' },
    { name: 'Windriders', role: 'Mounted' },
    { name: 'Wraithlord', role: 'Monster' },
    { name: 'Wraithknight', role: 'Monster' },
    { name: 'Wave Serpent', role: 'Vehicle' },
    { name: 'Falcon', role: 'Vehicle' },
    { name: 'Fire Prism', role: 'Vehicle' },
    { name: 'War Walker', role: 'Vehicle' },
  ],
  Drukhari: [
    { name: 'Lelith Hesperax', role: 'Epic Hero' },
    { name: 'Urien Rakarth', role: 'Epic Hero' },
    { name: 'Archon', role: 'Character' },
    { name: 'Succubus', role: 'Character' },
    { name: 'Haemonculus', role: 'Character' },
    { name: 'Kabalite Warriors', role: 'Battleline' },
    { name: 'Wyches', role: 'Infantry' },
    { name: 'Incubi', role: 'Infantry' },
    { name: 'Mandrakes', role: 'Infantry' },
    { name: 'Wracks', role: 'Infantry' },
    { name: 'Grotesques', role: 'Infantry' },
    { name: 'Scourges', role: 'Infantry' },
    { name: 'Kabalite Trueborn', role: 'Infantry' },
    { name: 'Reavers', role: 'Mounted' },
    { name: 'Hellions', role: 'Mounted' },
    { name: 'Raider', role: 'Vehicle' },
    { name: 'Venom', role: 'Vehicle' },
    { name: 'Ravager', role: 'Vehicle' },
    { name: 'Talos', role: 'Monster' },
    { name: 'Cronos', role: 'Monster' },
  ],
  'Tau Empire': [
    { name: 'Commander Farsight', role: 'Epic Hero' },
    { name: 'Commander Shadowsun', role: 'Epic Hero' },
    { name: 'Ethereal', role: 'Character' },
    { name: 'Cadre Fireblade', role: 'Character' },
    { name: 'Fire Warriors', role: 'Battleline' },
    { name: 'Breacher Team', role: 'Battleline' },
    { name: 'Strike Team', role: 'Battleline' },
    { name: 'Pathfinders', role: 'Infantry' },
    { name: 'Crisis Battlesuits', role: 'Infantry' },
    { name: 'Stealth Battlesuits', role: 'Infantry' },
    { name: 'Broadside Battlesuits', role: 'Infantry' },
    { name: 'Kroot Carnivores', role: 'Infantry' },
    { name: 'Vespid Stingwings', role: 'Infantry' },
    { name: 'Riptide Battlesuit', role: 'Monster' },
    { name: 'Ghostkeel Battlesuit', role: 'Monster' },
    { name: 'Devilfish', role: 'Vehicle' },
    { name: 'Hammerhead Gunship', role: 'Vehicle' },
    { name: 'Piranha', role: 'Vehicle' },
    { name: 'Sky Ray', role: 'Vehicle' },
  ],
  'Genestealer Cults': [
    { name: 'Patriarch', role: 'Epic Hero' },
    { name: 'Primus', role: 'Character' },
    { name: 'Magus', role: 'Character' },
    { name: 'Kelermorph', role: 'Character' },
    { name: 'Locus', role: 'Character' },
    { name: 'Neophyte Hybrids', role: 'Battleline' },
    { name: 'Acolyte Hybrids', role: 'Infantry' },
    { name: 'Purestrain Genestealers', role: 'Infantry' },
    { name: 'Aberrants', role: 'Infantry' },
    { name: 'Metamorphs', role: 'Infantry' },
    { name: 'Jackals', role: 'Infantry' },
    { name: 'Goliath Truck', role: 'Vehicle' },
    { name: 'Achilles Ridgerunner', role: 'Vehicle' },
    { name: 'Goliath Rockgrinder', role: 'Vehicle' },
  ],
  'Leagues of Votann': [
    { name: 'Pioneer Sergeant', role: 'Character' },
    { name: 'Hearthkyn Theign', role: 'Character' },
    { name: 'Hearthkyn Warriors', role: 'Battleline' },
    { name: 'Einhyr Champions', role: 'Infantry' },
    { name: 'Brôkhyr Thunderkyn', role: 'Infantry' },
    { name: 'Cthonian Beserks', role: 'Infantry' },
    { name: 'Hernkyn Yaegirs', role: 'Mounted' },
    { name: 'Hekaton Land Fortress', role: 'Vehicle' },
    { name: 'Sagitaur', role: 'Vehicle' },
  ],
};

// Chapter-specific troops, shown alongside the generic Space Marines list
// when that chapter is selected.
export const CHAPTER_UNIT_CATALOG: Record<string, CatalogUnit[]> = {
  'Blood Angels': [
    { name: 'The Sanguinor', role: 'Epic Hero' },
    { name: 'Commander Dante', role: 'Epic Hero' },
    { name: 'Mephiston, Lord of Death', role: 'Epic Hero' },
    { name: 'Astorath the Grim', role: 'Epic Hero' },
    { name: 'Lemartes', role: 'Character' },
    { name: 'Sanguinary Priest', role: 'Character' },
    { name: 'Sanguinary Ancient', role: 'Character' },
    { name: 'Death Company', role: 'Infantry' },
    { name: 'Death Company Intercessors', role: 'Infantry' },
    { name: 'Sanguinary Guard', role: 'Infantry' },
    { name: 'Death Company Dreadnought', role: 'Vehicle' },
    { name: 'Furioso Dreadnought', role: 'Vehicle' },
    { name: 'Baal Predator', role: 'Vehicle' },
  ],
  'Dark Angels': [
    { name: 'Azrael', role: 'Epic Hero' },
    { name: 'Belial', role: 'Epic Hero' },
    { name: 'Asmodai', role: 'Epic Hero' },
    { name: 'Interrogator-Chaplain', role: 'Character' },
    { name: 'Ezekiel', role: 'Character' },
    { name: 'Deathwing Knights', role: 'Infantry' },
    { name: 'Deathwing Terminator Squad', role: 'Infantry' },
    { name: 'Ravenwing Black Knights', role: 'Mounted' },
    { name: 'Ravenwing Bike Squad', role: 'Mounted' },
    { name: 'Ravenwing Darkshroud', role: 'Vehicle' },
    { name: 'Nephilim Jetfighter', role: 'Vehicle' },
  ],
  'Space Wolves': [
    { name: 'Logan Grimnar', role: 'Epic Hero' },
    { name: 'Ragnar Blackmane', role: 'Epic Hero' },
    { name: 'Njal Stormcaller', role: 'Epic Hero' },
    { name: 'Bjorn the Fell-Handed', role: 'Epic Hero' },
    { name: 'Arjac Rockfist', role: 'Epic Hero' },
    { name: 'Wolf Lord', role: 'Character' },
    { name: 'Iron Priest', role: 'Character' },
    { name: 'Lone Wolf', role: 'Character' },
    { name: 'Wulfen', role: 'Infantry' },
    { name: 'Wolf Guard Terminators', role: 'Infantry' },
    { name: 'Long Fangs', role: 'Infantry' },
    { name: 'Thunderwolf Cavalry', role: 'Mounted' },
  ],
  'Black Templars': [
    { name: 'High Marshal Helbrecht', role: 'Epic Hero' },
    { name: 'Marshal Grimaldus', role: 'Epic Hero' },
    { name: "Emperor's Champion", role: 'Character' },
    { name: 'Castellan', role: 'Character' },
    { name: 'Sword Brethren', role: 'Infantry' },
    { name: 'Primaris Crusader Squad', role: 'Battleline' },
  ],
  Deathwatch: [
    { name: 'Watch Master', role: 'Epic Hero' },
    { name: 'Watch Captain', role: 'Character' },
    { name: 'Deathwatch Veterans', role: 'Infantry' },
    { name: 'Deathwatch Terminators', role: 'Infantry' },
    { name: 'Deathwatch Kill Team', role: 'Infantry' },
    { name: 'Corvus Blackstar', role: 'Vehicle' },
  ],
};
